query ($handle: String!) {
    shop {
        productByHandle(handle: $handle) {
            id
            descriptionHtml
            handle
            productType
            title
            tags
            onlineStoreUrl
            options {
                name
            }
        }
    }
}